### ISSUE TITLE
build ffmpeg from a stable version

### ISSUE THREAD

**Issue by dunn** [acozine/sufia-centos#57]
What's the reason for building the `HEAD` of the ffmpeg repository instead of the latest stable version?

**Comment by acozine** [comment]
Partly following online documentation, partly wanting to use the latest of everything, and partly not wanting to have zillions of version variables.
The approach has lasted this long because we have not seen failures with ffmpeg itself, only with the libraries it uses. 
That said, I'm in favor of specifying a version.

**Comment by dunn** [comment]
https://github.com/acozine/sufia-centos/commit/31f220ed0681155624ff1708c58a4a71873066fd
